package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// CronJob is one user-defined scheduled task that will run inside the PHP
// container via supercronic. The schedule is a standard 5-field cron
// expression (minimum interval: 1 minute). The command is executed with
// `bash -lc` from /var/www/html so `drush` and vendor/bin are on PATH.
type CronJob struct {
	Name     string `json:"name"`
	Schedule string `json:"schedule"`
	Command  string `json:"command"`
	Enabled  bool   `json:"enabled"`
}

// CrontabHostPath is where the crontab file lives on the VM host. It is
// mounted read-only into the PHP container at CrontabContainerPath.
const (
	CrontabHostPath      = "/var/www/preview/crontab"
	CrontabContainerPath = "/etc/supercronic/crontab"
	SupercronicLogPath   = "/var/log/supercronic.log"
)

// WriteCrontab writes the user-defined cron jobs to the host path. It always
// writes the file (even if jobs is empty) so the container's bind mount is
// never missing. Disabled jobs should already be filtered out by the server
// before the payload reaches the agent.
func WriteCrontab(jobs []CronJob) error {
	var b strings.Builder
	b.WriteString("# Generated by druploy-agent. Do not edit by hand.\n")
	b.WriteString("# Each job runs from /var/www/html as www-data.\n")
	b.WriteString("# Schedule | Command\n\n")

	for _, j := range jobs {
		if !j.Enabled {
			continue
		}
		// Wrap with cd + bash -lc so PATH (vendor/bin, nvm) and drush work.
		// Tag the line with the job name so supercronic's log is searchable.
		line := fmt.Sprintf(
			"%s /bin/bash -lc %q\n",
			j.Schedule,
			fmt.Sprintf("cd /var/www/html && %s", j.Command),
		)
		b.WriteString(fmt.Sprintf("# job: %s\n", j.Name))
		b.WriteString(line)
	}

	if err := os.MkdirAll("/var/www/preview", 0755); err != nil {
		return fmt.Errorf("mkdir preview dir: %w", err)
	}
	if err := os.WriteFile(CrontabHostPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write crontab: %w", err)
	}
	return nil
}

// ReloadSupercronic restarts the supercronic process inside the PHP container
// so it picks up the new crontab. It tolerates the "not running" case (first
// deploy or user had no cron jobs).
func ReloadSupercronic(phpContainer string) error {
	// Kill any existing supercronic. || true because it may not be running.
	killCmd := exec.Command("docker", "exec", phpContainer,
		"bash", "-c", "pkill -f supercronic || true")
	killCmd.Dir = "/"
	_ = killCmd.Run()

	// Start supercronic in background. We use nohup + setsid so it survives
	// the docker exec session closing. Logs go to /var/log/supercronic.log.
	// `-overlapping=false` is the default but we set it explicitly for clarity:
	// if the previous run of a job is still in flight, skip the next tick.
	startShell := fmt.Sprintf(
		"if [ -s %s ]; then "+
			"nohup setsid /usr/local/bin/supercronic -passthrough-logs %s "+
			">> %s 2>&1 < /dev/null & "+
			"fi",
		CrontabContainerPath, CrontabContainerPath, SupercronicLogPath,
	)
	startCmd := exec.Command("docker", "exec", "-d", phpContainer, "bash", "-c", startShell)
	startCmd.Dir = "/"
	if err := startCmd.Run(); err != nil {
		return fmt.Errorf("start supercronic: %w", err)
	}
	return nil
}
