---
- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: Restart druploy
  systemd:
    name: druploy
    state: restarted
  become: yes

- name: Restart druploy-worker
  systemd:
    name: druploy-worker
    state: restarted
  become: yes
