package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// resolvePreviewTarget resolves the project and preview name from args or auto-detection.
func resolvePreviewTarget(args []string) (project, previewName string, err error) {
	if len(args) == 1 {
		project, previewName, err = parsePreviewName(args[0])
		if err != nil {
			return "", "", err
		}
		if err := resolveOrgForProject(project); err != nil {
			return "", "", err
		}
		return project, previewName, nil
	}

	// Auto-detect project from git remote
	project, err = detectProjectSlug()
	if err != nil {
		return "", "", err
	}

	if err := resolveOrgForProject(project); err != nil {
		return "", "", err
	}

	// Auto-detect branch
	branch, err := detectGitBranch()
	if err != nil {
		return "", "", err
	}
	fmt.Fprintf(os.Stderr, "Detected branch: %s\n", branch)

	// Find preview matching this branch
	preview, err := findPreviewByBranch(project, branch)
	if err != nil {
		return "", "", err
	}
	fmt.Fprintf(os.Stderr, "Found preview: %s (branch: %s)\n", preview.Name, preview.Branch)

	return project, preview.Name, nil
}

var genAliasesCmd = &cobra.Command{
	Use:   "gen-drush-aliases [PROJECT/PREVIEW-NAME]",
	Short: "Generate local drush site aliases for a preview",
	Long: `Generate a drush/sites/druploy.site.yml file with aliases pointing
to the preview environment, including SSH connection info for remote drush.

If PROJECT/PREVIEW-NAME is given, uses that specific preview.
If no argument is given, auto-detects from git remote and current branch.

The generated file is written to drush/sites/druploy.site.yml relative
to the git repository root.

Examples:
  druploy gen-drush-aliases
  druploy gen-drush-aliases soudal/branch-SDLMNT-4-Drupal-11-Upgrade`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		project, previewName, err := resolvePreviewTarget(args)
		if err != nil {
			return err
		}

		detail, err := apiClient.GetPreview(project, previewName)
		if err != nil {
			return fmt.Errorf("failed to get preview details: %w", err)
		}

		if detail.UrlHash == "" {
			return fmt.Errorf("preview %s/%s has no url_hash — is it deployed?", project, previewName)
		}

		if detail.VmIP == "" {
			return fmt.Errorf("preview %s/%s has no VM assigned — is it deployed?", project, previewName)
		}

		// Fetch preview config from VM agent (domain_aliases, docroot)
		previewConfig, err := apiClient.GetPreviewConfig(project, previewName)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: could not fetch preview config: %v\n", err)
			fmt.Fprintf(os.Stderr, "Generating aliases without domain aliases.\n")
		}

		// Inject SSH key into the preview so aliases work immediately
		publicKey := getLocalSSHPublicKey()
		if publicKey != "" {
			if err := apiClient.InjectSSHKey(project, previewName, publicKey); err != nil {
				fmt.Fprintf(os.Stderr, "Warning: could not inject SSH key: %v\n", err)
			}
		}

		domain := fmt.Sprintf("%s.druploy.dev", detail.UrlHash)

		// SSH options: direct SSH to VM on port 2222 (sshd inside PHP container)
		sshOpts := "-p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"

		// Build aliases: default + domain aliases
		type alias struct {
			name string
			uri  string
		}
		var aliases []alias

		aliases = append(aliases, alias{"default", fmt.Sprintf("https://%s", domain)})

		// Add domain aliases from preview config
		if previewConfig != nil && len(previewConfig.DomainAliases) > 0 {
			sorted := make([]string, len(previewConfig.DomainAliases))
			copy(sorted, previewConfig.DomainAliases)
			sort.Strings(sorted)
			for _, prefix := range sorted {
				aliases = append(aliases, alias{prefix, fmt.Sprintf("https://%s--%s", prefix, domain)})
			}
		} else {
			// Fallback: use domain aliases from the preview detail (already resolved URLs)
			var prefixes []string
			for prefix := range detail.DomainAliases {
				prefixes = append(prefixes, prefix)
			}
			sort.Strings(prefixes)
			for _, prefix := range prefixes {
				aliases = append(aliases, alias{prefix, detail.DomainAliases[prefix]})
			}
		}

		// Generate YAML manually
		var buf strings.Builder
		buf.WriteString("# Generated by: druploy gen-drush-aliases\n")
		buf.WriteString(fmt.Sprintf("# Preview: %s/%s (branch: %s)\n", project, previewName, detail.Branch))
		buf.WriteString("# Re-run the command to update after a rebuild.\n")
		// Determine Drupal root from docroot config
		drupalRoot := "/var/www/html"
		if previewConfig != nil && previewConfig.Docroot != "" && previewConfig.Docroot != "." {
			drupalRoot = "/var/www/html/" + previewConfig.Docroot
		}

		for _, a := range aliases {
			buf.WriteString(fmt.Sprintf("%s:\n", a.name))
			buf.WriteString(fmt.Sprintf("  uri: '%s'\n", a.uri))
			buf.WriteString(fmt.Sprintf("  root: %s\n", drupalRoot))
			buf.WriteString(fmt.Sprintf("  host: %s\n", detail.VmIP))
			buf.WriteString("  user: preview\n")
			buf.WriteString("  ssh:\n")
			buf.WriteString(fmt.Sprintf("    options: '%s'\n", sshOpts))
			buf.WriteString("  paths:\n")
			buf.WriteString("    drush-script: vendor/bin/drush\n")
		}

		// Find git root
		rootBytes, err := exec.Command("git", "rev-parse", "--show-toplevel").Output()
		if err != nil {
			return fmt.Errorf("not in a git repository")
		}
		gitRoot := strings.TrimSpace(string(rootBytes))

		// Write to drush/sites/druploy.site.yml
		drushDir := filepath.Join(gitRoot, "drush", "sites")
		if err := os.MkdirAll(drushDir, 0755); err != nil {
			return fmt.Errorf("failed to create drush/sites/: %w", err)
		}

		aliasFile := filepath.Join(drushDir, "druploy.site.yml")
		if err := os.WriteFile(aliasFile, []byte(buf.String()), 0644); err != nil {
			return fmt.Errorf("failed to write %s: %w", aliasFile, err)
		}

		// Show result
		relPath, _ := filepath.Rel(gitRoot, aliasFile)
		fmt.Fprintf(os.Stderr, "Written to %s\n\n", relPath)
		fmt.Fprintf(os.Stderr, "Available aliases:\n")
		for _, a := range aliases {
			fmt.Fprintf(os.Stderr, "  @preview.%-12s %s\n", a.name, a.uri)
		}
		fmt.Fprintf(os.Stderr, "\nTest with: drush @preview.default status\n")

		return nil
	},
}

func init() {
	rootCmd.AddCommand(genAliasesCmd)
}
